### ISSUE TITLE
How refactor project to a standard python package?

### ISSUE THREAD

**Issue by ryukinix** [gciruelos/musthe#12]
I was wondering about that because I wanna put on Arch Linux Repository and provide too a simple command line interface to do some cool stuff like: 

```
> musthe scale c-major
C D E F G A B
```

How about that?

**Comment by gciruelos** [comment]
Sure. I don't have much time right now to do that. Contributions are welcome though.

**Comment by zsinx6** [comment]
I'll refactor and create a setup to upload it on https://pypi.org/

**Comment by gciruelos** [comment]
thanks @zsinx6 , I'm closing this now.
