### ISSUE TITLE
error: interval d3

### ISSUE THREAD

**Issue by fferri** [gciruelos/musthe#14]
**d3** should be 2 semitones, not 3

(line 144 of musthe/musthe.py)

Reference: intervals table in https://en.wikipedia.org/wiki/Interval_(music)#Main_intervals

**Comment by gciruelos** [comment]
again, do a pull request with your fix if you want, i'll add you to the contributors list :)

**Comment by nvoster** [comment]
I just submitted a pull request that includes this fix
