### ISSUE TITLE
Conflicting repositories

### ISSUE THREAD

**Issue by zsinx6** [gciruelos/musthe#17]
@gciruelos Could you merge from https://github.com/nvoster/musthe ? I would like to contribute, but it doesnt seem right to just start working on @nvoster

**Comment by nvoster** [comment]
@zsinx6 feel free to work from my repo, I'll stay fairly active on it. gciruelos is the master and a lot have branched off, so I'm not sure if gciruelos merging my repo is the best solution.

**Comment by gciruelos** [comment]
Hi all,
do a pull request and I'll gladly merge it if it looks good.
